services:
  postgres:
    image: postgres:15
    container_name: pql-template-container
    restart: always
    environment:
      POSTGRES_DB: pql-template-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pg-template-v:/var/lib/postgresql/data

volumes:
  pg-template-v: 
